### ISSUE TITLE
Render themes: line symbol

### ISSUE THREAD

**Issue by andreynovikov** [mapsforge/vtm#124]
https://github.com/mapsforge/vtm/blob/master/vtm/src/org/oscim/theme/XmlThemeBuilder.java#L258

Useful for aerialway icons.

**Comment by devemux86** [comment]
And oneways too!

Line symbol is coming from Mapsforge and I'm not sure we need to have it as a new tag.
Line texture can suffice, provided that we enhance the stipple attributes with a [repeat-gap](https://github.com/mapsforge/mapsforge/blob/master/resources/renderTheme-v5.xsd#L206).
Currently `stipple` attribute plays the role of both the gap and the texture length.

**Comment by andreynovikov** [comment]
Not really. Line texture is aligned (rotated) along line. Line symbol should remain vertical, like node symbol.

**Comment by devemux86** [comment]
Actually in Mapsforge we have an extra attribute [rotate](https://github.com/mapsforge/mapsforge/blob/master/resources/renderTheme-v5.xsd#L208) for that, with default behavior to be aligned with the line.

**Comment by andreynovikov** [comment]
Then ok, will wait for implementation.

**Comment by Klaus-Tockloth** [comment]
I use lineSymbol for cliffs and for one-way streets. It would be great if this feature could be implemented.

![bildschirmfoto 2016-10-29 um 21 07 17](https://cloud.githubusercontent.com/assets/5493128/19832124/d9719de8-9e1b-11e6-90b4-3af8b2de84f5.jpg)

![bildschirmfoto 2016-10-29 um 21 06 31](https://cloud.githubusercontent.com/assets/5493128/19832126/de5a7000-9e1b-11e6-8764-4925c6f96b43.jpg)

**Comment by devemux86** [comment]
Thanks to PR #388 by @Longri for Mapsforge theme compatibility, we have now an implementation of line symbols also in VTM themes.

**Comment by devemux86** [comment]
cc @Longri
Oneways don't render correctly, could need more work.

**Comment by devemux86** [comment]
I pushed the needed fixes for line symbols.

**Comment by devemux86** [comment]
Oneways with the `lineSymbol` rule:

![oneways](https://user-images.githubusercontent.com/3484020/30782815-c75e0ffe-a141-11e7-9b03-b769501c06d2.png)

**Comment by andreynovikov** [comment]
Have tried this new feature for cliffs and failed. Looks like `repeat-gap` with value less then 30 does not work. I've thought it's because of `repeat-start`, have set it to 0 but still get too large gaps between symbols.

**Comment by devemux86** [comment]
Isn't the [natural=cliff](http://wiki.openstreetmap.org/wiki/Tag:natural%3Dcliff) rendering supposed to be with symbols having some distance among them?

Also it depends on symbols quality. If the symbols have much empty space around in their canvas, then they cannot be much close, even if put small `repeat-gap`.

**Comment by andreynovikov** [comment]
Yes. But the distance is too large. I use square icon with a tick: https://github.com/andreynovikov/maptrek/blob/master/app/src/main/assets/symbols/natural/cliff.svg There is no much space around. But the gap between symbols is about 1 centimeter on smartphone screen.

**Comment by devemux86** [comment]
Trying even with the [oneway](https://github.com/mapsforge/vtm/blob/master/vtm-themes/resources/assets/symbols/oneway.svg) symbol which doesn't have empty canvas at its width and with `repeat-gap="0" repeat-start="0"`, we cannot achieve continuous symbols rendering.

That seems related to the underlying stipples mechanism and not with line symbols (using it).
You can create a new issue to check it there.
